config/routes.rb
Rails.application.routes.draw do
    resources :sessions, only: [:new, :create, :destroy]

  resources :users do 
  	resources :reservations
  end
  resources :restaurants do 
  	resources :reservations	
    resources :reviews, only: [:show, :create, :destroy]
  end 
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
	belongs_to :user
	belongs_to :restaurant
	validates :time, numericality: {only_integer: true, greater_than: 11, less_than: 22}
	validates :party_size, numericality: {only_integer: true, greater_than: 1, less_than: 21}
	validates :date, :user, presence: true
	validate :date_must_be_between, :date_cannot_be_in_the_past
	validate :availability
	
	private
	def date_must_be_between
		errors.add(:date, "is too far away. Only book one month ahead.") unless date < Date.today + 1.month
	end

	def date_cannot_be_in_the_past
		errors.add(:date, "cannot be in the past. Booking starts with today date.") unless date >= Date.today
	end 
	
	def availability 
		other_people = restaurant.reservations.where(time: time).sum(:party_size)

		if (other_people + party_size) > restaurant.capacity
			errors.add(:base, "Sorry, the restaurant is booked for this hour")
		end
	end

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
has_many :reservations
has_many :reviews
has_many :users, through: :reviews
end

app/models/review.rb
class Review < ActiveRecord::Base
scope :newest_first, -> {order("created_at DESC")}
belongs_to :restaurant
belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :reservations
	has_many :reviews
	has_many :restaurants, through: :reviews 
	validates :email, uniqueness: true
	validates :password, confirmation: true
	validates :password_confirmation, presence: true
	validates :password, length: {in: 4..20}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

def ensure_logged_in
    unless current_user
      flash[:alert] = "Please log in"
      redirect_to new_session_path
    end
  end

private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
	before_filter :load_restaurant, :load_user
	before_filter :ensure_logged_in, only: [:create, :destroy]

	def index 
		@reservations = @model.reservations
	end
	
	def create
		 @reservation = Reservation.new(reservation_params)
		 @reservation.restaurant = @model
		 @reservation.user = current_user
		
		if @reservation.save
			redirect_to user_reservation_path(current_user, @reservation)
		else 
			@restaurant = @model
			@review = Review.new
			render 'restaurants/show'
		end 
	end	

	def show
		@reservation = Reservation.find(params[:id])
	end
	
	def edit 
		@reservation = Reservation.find(params[:id])
		@restaurant = @reservation.restaurant
		render "restaurants/show"
	end
	
	def update
		@reservation = Reservation.find(params[:id])

		if @reservation.update_attributes(reservation_params)
			flash[:notice] = "Reservation created!"
			redirect_to user_reservation_path(current_user, @reservation)
		else
			render "restaurants/show"
		end 
	end
	
	def destroy
		@reservation = Reservation.find(params[:id])
		@reservation.destroy
		redirect_to restaurants_path
	end 

	private
	def reservation_params
		params.require(:reservation).permit(:time, :date, :party_size)
	end

	# Skip loading model if <association>_id is missing
	# from params

	# Restaurant and User both share an association:
	# - reservations
	# so we can leverage that in our views by using
	# a generic model name.
	# model name could probably be improved
	# comments in source code are terrible
	def load_restaurant
		return unless params[:restaurant_id]
		@model = Restaurant.find(params[:restaurant_id]) 
	end

	def load_user
		return unless params[:user_id]
		@model = User.find(params[:user_id])
	end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
	def index 
		@restaurants = Restaurant.all
	end
	
	def new
		@restaurant = Restaurant.new
	end
	
	def create
	 @restaurant = Restaurant.new(restaurant_params)
		
		if @restaurant.save
		   redirect_to restaurants_url
		else 
		    render :new
		end 
	end	

	def show
		if params[:restaurant_id]
			# nested (/restaruants/:restaurant_id/reservations/:id)
			@restaurant = Restaurant.find(params[:restaurant_id])
			@reservation = @restaurant.reservations.find(params[:id])
		else
			# just /restaurant/:id
			@restaurant = Restaurant.find(params[:id])
			@reservation = Reservation.new
		end
		@review = Review.new
	end
	
	def edit 
		@restaurant = Restaurant.find(params[:id])
	end
	
	def update
		@restaurant = Restaurant.new(restaurant_params)

		if @restaurant.update_attributes(restaurant_params)
			redirect_to restaurant_path(@restaurant)
		else
			render :edit
		end 
	end
	
	def destroy
		@restaurant = Restaurant.find(params[:id])
		@restaurant.destroy
		redirect_to restaurants_path
	end 

	private
	def restaurant_params
		params.require(:restaurant).permit(:name, :summary, :phone, :address, :capacity)
	end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_filter :load_restaurant 
	before_filter :ensure_logged_in, only: [:create, :destroy]
  
  def show
  	@review = Review.find(params[:id])
  end

  def create
  	@review = @restaurant.reviews.build(review_params)
  	@review.user = current_user

  	if @review.save
  		redirect_to restaurants_path, notice: 'Review created successfully'
  	else 
  		render 'restaurants/show'
  	end 
  end

  def destroy
  	@review = Review.find(params[:id])
  	@review.destroy
  end

  private
  def review_params 
  	params.require(:review).permit(:comment, :restaurant_id)
  end 

  def load_restaurant
  	@restaurant = Restaurant.find(params[:restaurant_id])
  end 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
  	end

  	def create
    	user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to restaurants_url, notice: "Logged in!"
    else
      flash.now[:alert] = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to restaurants_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index 
	#	@reservations = current_user.reservations
	end
	
	def new
		@user = User.new
	end
	
	def create
	 @user = User.new(user_params)
		
		if @user.save
		   redirect_to restaurants_path, notice: "Signed up!"
		else 
		    render :new
		end 
	end	

	def show
		@user = User.find(params[:id])
	end
	
	def edit 
		@user = User.find(params[:id])
	end
	
	def update
		@user = User.new(user_params)

		if @user.update_attributes(user_params)
			redirect_to user_path(@user)
		else
			render :edit
		end 
	end
	
	def destroy
		@user = User.find(params[:id])
		@user.destroy
		redirect_to root_path
	end 

	private
	def user_params
		params.require(:user).permit(:first_name, :last_name, :phone, :email, :password, :password_confirmation)
	end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Seatyourself</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if flash[:notice] %>
      <p id="notice"><%= flash[:notice] %></p>
    <% end %>
    <% if flash[:alert] %>
      <p id="alert"><%= flash[:alert] %></p>
    <% end %>

<p class="userinfo">
      <% if current_user %>
        Signed in as 
          <%= current_user.first_name %>. 
          <%= link_to "Log out", session_path("current"), :method => :delete %>
          |
          <%= link_to "My reservations", user_reservations_path(current_user) %>
      <% else %>
        <%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %>
      <% end %></p>
<%= yield %>
</body>
</html>

app/views/reservations/_errornotice.html.erb
  <% if @reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% @reservation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

app/views/reservations/_reservation.html.erb
<div style="background-color: #fee; display: table;">
	<%= render reservation.restaurant %>
	<h3>Reserved on <%= reservation.date %> at <%= reservation.time %>00 hours 
	for <%= reservation.party_size %> people.
</div>

<%= link_to "Edit", [current_user, reservation], method: :patch %> 
	| 
<%= link_to "Delete", [current_user, reservation], method: :delete %>

app/views/reservations/index.html.erb
<h3> All the reservations for <%= current_user.first_name %></h3>

<% @reservations.each do |reservation| %>
	<%= render reservation %>
<% end %>

app/views/reservations/show.html.erb
<h1> Your Table has been reserved!</h1>

<%= render @reservation %>

<%= link_to "Back to reserve more...", restaurants_url %>

<h2> Your other reservations for this month: </h2>

<%= render current_user.reservations - [@reservation] %>

app/views/restaurants/_form.html.erb
<%= form_for @restaurant do |f| %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :summary %><br />
    <%= f.text_area :summary %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
   <div class="field">
    <%= f.label :phone %><br />
    <%= f.phone_field :phone %>
  </div>
   <div class="field">
    <%= f.label :capacity %><br />
    <%= f.number_field :capacity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurants/_new_reservation_form.html.erb
<h1> Create new reservation</h1>

<%= form_for [owner, reservation] do |f| %>
<%= render partial: 'reservations/errornotice' %>
  <div class="field">
    <%= f.label :time %><br />
    <%= f.number_field :time %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :party_size %><br />
    <%= f.number_field :party_size %>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurants/_restaurant.html.erb
<div style="background-color: #eee; display: table;">
	<h2><%= link_to restaurant.name, restaurant %></h2>

	<ul>
		<p>
			<li>Address: <%= restaurant.address %></li> 
			<li>Phone: <%= restaurant.phone %></li> 
			<li>Summary: <%= restaurant.summary %></li> 
		</p>
	</ul>
</div>

app/views/restaurants/edit.html.erb
<%= render partial: "restaurants/form" %>

app/views/restaurants/index.html.erb
<h1> List of Restaurants </h1>
<h2> Please, choose a restaurant you want to book: </h2>

<%= render @restaurants %>

app/views/restaurants/new.html.erb
<%= link_to "Back to restaurants", restaurants_url %>

<%= render partial: "restaurants/form" %>

app/views/restaurants/show.html.erb
<%= render @restaurant %>

<%= link_to "Back to Restaurants", restaurants_url %> 

<%= render partial: 'restaurants/new_reservation_form', locals: {owner: @restaurant, reservation: @reservation} %>


  <h3>Reviews for <%= @restaurant.name %></h3>

  <%= render @restaurant.reviews %>

  <% if current_user %>
  <h4>New Review</h4>

  <%= form_for([@restaurant, @review]) do |f| %>
    <% if @review.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

        <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :comment %><br />
      <%= f.text_area :comment %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

<% else %>
  <p>Please <%= link_to "log in", new_session_path %> to add a review or to make a reservation.</p> 
<% end %>

app/views/reviews/_review.html.erb
<div style="background-color: #eef; display: table;">
<p>
	<%= review.user.first_name %> (posted at <%= review.created_at %>)
</p>

<p>
<%= review.comment %>
</p>
</div>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/destroy.html.erb
<h1>Reviews#destroy</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

app/views/users/edit.html.erb
  <%= form_for @user do |f| %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.telephone_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
   <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
   <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>


<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.telephone_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
   <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
   <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1> Show User </h1>

<ul>
	<p> <li><%= @user.first_name %></li> 
		<li><%= @user.last_name %></li> 
		<li><%= @user.phone %></li> 
		<li><%= @user.email %></li> 
	</p>
</ul>

 <%= link_to "Edit", edit_user_path(@user) %> | <%= link_to "Delete", @user, method: :delete, data: {confirm: "Are you sure you want to delete your profile?"}  %>